# Generated by Django 4.1 on 2022-08-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('TW', 'Two'), ('TH', 'Three'), ('FO', 'Four')], max_length=2)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
